version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`ss
      - docker build -t group2c2danhtodo:latest .
      - docker tag group2c2danhtodo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2c2-danh-repo:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2c2-danh-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"group2c2danhtodo","imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/group2c2-danh-repo"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json